# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Add_Type_Breed.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_winAddTypeBreed(object):
    def setupUi(self, winAddTypeBreed):
        winAddTypeBreed.setObjectName("winAddTypeBreed")
        winAddTypeBreed.resize(310, 103)
        winAddTypeBreed.setStyleSheet("background-color: rgb(150, 255, 84);")
        self.label = QtWidgets.QLabel(winAddTypeBreed)
        self.label.setGeometry(QtCore.QRect(11, 20, 49, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.entry = QtWidgets.QLineEdit(winAddTypeBreed)
        self.entry.setGeometry(QtCore.QRect(65, 20, 220, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.entry.setFont(font)
        self.entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry.setObjectName("entry")
        self.btnSave = QtWidgets.QPushButton(winAddTypeBreed)
        self.btnSave.setGeometry(QtCore.QRect(130, 46, 50, 50))
        self.btnSave.setStatusTip("")
        self.btnSave.setText("")
        icon = QtGui.QIcon.fromTheme("C:\\Users\\baris\\Desktop\\Projects\\Vet\\Icons\\save.png")
        self.btnSave.setIcon(icon)
        self.btnSave.setIconSize(QtCore.QSize(40, 40))
        self.btnSave.setFlat(True)
        self.btnSave.setObjectName("btnSave")

        self.retranslateUi(winAddTypeBreed)
        QtCore.QMetaObject.connectSlotsByName(winAddTypeBreed)

    def retranslateUi(self, winAddTypeBreed):
        _translate = QtCore.QCoreApplication.translate
        winAddTypeBreed.setWindowTitle(_translate("winAddTypeBreed", "Add"))
        self.label.setText(_translate("winAddTypeBreed", "Name:"))
        self.btnSave.setToolTip(_translate("winAddTypeBreed", "Save"))
