# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Appointments.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_winAppointments(object):
    def setupUi(self, winAppointments):
        winAppointments.setObjectName("winAppointments")
        winAppointments.resize(600, 315)
        winAppointments.setMinimumSize(QtCore.QSize(600, 315))
        winAppointments.setMaximumSize(QtCore.QSize(600, 315))
        self.tbwAppointments = QtWidgets.QTableWidget(winAppointments)
        self.tbwAppointments.setGeometry(QtCore.QRect(20, 10, 560, 295))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.tbwAppointments.setFont(font)
        self.tbwAppointments.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"color: rgb(52, 17, 200);")
        self.tbwAppointments.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbwAppointments.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbwAppointments.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbwAppointments.setObjectName("tbwAppointments")
        self.tbwAppointments.setColumnCount(4)
        self.tbwAppointments.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(2, 222, 222))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tbwAppointments.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(2, 222, 222))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tbwAppointments.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(2, 222, 222))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tbwAppointments.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(2, 222, 222))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tbwAppointments.setHorizontalHeaderItem(3, item)

        self.retranslateUi(winAppointments)
        QtCore.QMetaObject.connectSlotsByName(winAppointments)

    def retranslateUi(self, winAppointments):
        _translate = QtCore.QCoreApplication.translate
        winAppointments.setWindowTitle(_translate("winAppointments", "Coming Appointments"))
        item = self.tbwAppointments.horizontalHeaderItem(0)
        item.setText(_translate("winAppointments", "ID"))
        item = self.tbwAppointments.horizontalHeaderItem(1)
        item.setText(_translate("winAppointments", "Appointment For"))
        item = self.tbwAppointments.horizontalHeaderItem(2)
        item.setText(_translate("winAppointments", "Vaccine"))
        item = self.tbwAppointments.horizontalHeaderItem(3)
        item.setText(_translate("winAppointments", "Date of Appointment"))
