# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Win.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_winMain(object):
    def setupUi(self, winMain):
        winMain.setObjectName("winMain")
        winMain.resize(300, 371)
        icon = QtGui.QIcon.fromTheme("C:\\Users\\baris\\Desktop\\Projects\\Vet\\Icons\\IDEAL_ICON_2.ico")
        winMain.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(winMain)
        self.centralwidget.setObjectName("centralwidget")
        self.btnUsers = QtWidgets.QPushButton(self.centralwidget)
        self.btnUsers.setGeometry(QtCore.QRect(100, 150, 100, 29))
        font = QtGui.QFont()
        font.setFamily("Britannic Bold")
        font.setPointSize(12)
        self.btnUsers.setFont(font)
        self.btnUsers.setStyleSheet("background-color: rgb(106, 208, 255);\n"
"color: rgb(30, 30, 86);")
        self.btnUsers.setObjectName("btnUsers")
        self.btnParOfEduc = QtWidgets.QPushButton(self.centralwidget)
        self.btnParOfEduc.setGeometry(QtCore.QRect(50, 100, 200, 29))
        font = QtGui.QFont()
        font.setFamily("Britannic Bold")
        font.setPointSize(12)
        self.btnParOfEduc.setFont(font)
        self.btnParOfEduc.setStyleSheet("background-color: rgb(106, 208, 255);\n"
"color: rgb(30, 30, 86);")
        self.btnParOfEduc.setObjectName("btnParOfEduc")
        self.btnClPetInfo = QtWidgets.QPushButton(self.centralwidget)
        self.btnClPetInfo.setGeometry(QtCore.QRect(50, 50, 200, 29))
        font = QtGui.QFont()
        font.setFamily("Britannic Bold")
        font.setPointSize(12)
        self.btnClPetInfo.setFont(font)
        self.btnClPetInfo.setStyleSheet("background-color: rgb(106, 208, 255);\n"
"color: rgb(30, 30, 86);")
        self.btnClPetInfo.setObjectName("btnClPetInfo")
        self.lblBackground = QtWidgets.QLabel(self.centralwidget)
        self.lblBackground.setGeometry(QtCore.QRect(-370, -62, 700, 525))
        self.lblBackground.setText("")
        self.lblBackground.setPixmap(QtGui.QPixmap("../../../../../../D/Pictures & Stuff/The Deepest, Sharpest Infrared Image of the Universe.jpg"))
        self.lblBackground.setScaledContents(True)
        self.lblBackground.setObjectName("lblBackground")
        self.lblBackground.raise_()
        self.btnUsers.raise_()
        self.btnParOfEduc.raise_()
        self.btnClPetInfo.raise_()
        winMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(winMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setObjectName("menubar")
        winMain.setMenuBar(self.menubar)

        self.retranslateUi(winMain)
        QtCore.QMetaObject.connectSlotsByName(winMain)

    def retranslateUi(self, winMain):
        _translate = QtCore.QCoreApplication.translate
        winMain.setWindowTitle(_translate("winMain", "Cosmos Vet Clinic -"))
        self.btnUsers.setText(_translate("winMain", "Users"))
        self.btnParOfEduc.setText(_translate("winMain", "Participants of Education"))
        self.btnClPetInfo.setText(_translate("winMain", "Clients && Pets Information"))
