# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Reminder.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_winApporachingAppointments(object):
    def setupUi(self, winApporachingAppointments):
        winApporachingAppointments.setObjectName("winApporachingAppointments")
        winApporachingAppointments.resize(348, 136)
        self.lblMsg = QtWidgets.QLabel(winApporachingAppointments)
        self.lblMsg.setGeometry(QtCore.QRect(42, 18, 267, 37))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblMsg.setFont(font)
        self.lblMsg.setStyleSheet("color: rgb(58, 84, 255)")
        self.lblMsg.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMsg.setObjectName("lblMsg")
        self.btnYes = QtWidgets.QPushButton(winApporachingAppointments)
        self.btnYes.setGeometry(QtCore.QRect(108, 100, 50, 21))
        font = QtGui.QFont()
        font.setFamily("Britannic Bold")
        font.setPointSize(12)
        self.btnYes.setFont(font)
        self.btnYes.setStyleSheet("background-color: rgb(82, 255, 2);")
        self.btnYes.setObjectName("btnYes")
        self.btnNo = QtWidgets.QPushButton(winApporachingAppointments)
        self.btnNo.setGeometry(QtCore.QRect(178, 100, 50, 21))
        font = QtGui.QFont()
        font.setFamily("Britannic Bold")
        font.setPointSize(12)
        self.btnNo.setFont(font)
        self.btnNo.setStyleSheet("background-color:rgb(236, 0, 0);\n"
"")
        self.btnNo.setObjectName("btnNo")
        self.cbRemind = QtWidgets.QCheckBox(winApporachingAppointments)
        self.cbRemind.setGeometry(QtCore.QRect(56, 66, 229, 19))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.cbRemind.setFont(font)
        self.cbRemind.setObjectName("cbRemind")

        self.retranslateUi(winApporachingAppointments)
        QtCore.QMetaObject.connectSlotsByName(winApporachingAppointments)

    def retranslateUi(self, winApporachingAppointments):
        _translate = QtCore.QCoreApplication.translate
        winApporachingAppointments.setWindowTitle(_translate("winApporachingAppointments", "Apporaching Appointments"))
        self.lblMsg.setText(_translate("winApporachingAppointments", "You have \"0\" approaching appointments.\n"
"Do you want to see them?"))
        self.btnYes.setText(_translate("winApporachingAppointments", "YES"))
        self.btnNo.setText(_translate("winApporachingAppointments", "NO"))
        self.cbRemind.setText(_translate("winApporachingAppointments", "Do not remind again for today"))
